site_name: MrFlwrz Destiny 2 Guides # Change this to your site name
site_description: Sherpa advice and guides for activities!
site_url: https://audiolotus.github.io/FlwrzD2 # Change this to your site URL
site_author: Flowers

theme:
  name: 'material'
  logo: 
  favicon: 
  custom_dir: overrides
  font:
      text: Ubuntu
      code: Ubuntu Mono
  language: en
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

# Extensions
markdown_extensions:
#Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - mdx_breakless_lists  
  - meta  
  - nl2br
  - sane_lists
  - smarty
  - tables
  - toc:
      permalink: true

#Python Markdown Ext
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case:lower

plugins:
  - awesome-pages
  - callouts
  - custom-attributes:
      file: 'assets/css/custom_attributes.css'
  - embed_file:
      callouts: true
      custom-attributes: 'assets/css/custom_attributes.css'
  - ezlinks:
        wikilinks: true
  - glightbox
  - meta-descriptions
  - search
    enabled:false

hooks:
  - overrides/hooks/on_page_markdown.py
  - overrides/hooks/on_env.py
  - overrides/hooks/on_files.py

extra_javascript:
  - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/javascript.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - https://cdn.jsdelivr.net/gh/ObsidianPublisher/assets@main/dist/styles.css
    - assets/css/admonition.css
    - assets/css/custom_attributes.css
    - assets/css/customization.css

extra:
  SEO: assets/meta/SEO.png
  comments: False #disable comments globally
  generate_graph: false #generate the graph of the site
  attachments: 'assets/img' #path to the folder where the attachments are stored
  no-auto-h1: False #disable the automatic generation of h1 if no h1 is found
  
  hooks:
    strip_comments: true
    fix_heading: true

  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/SJujZm2WDw